### ISSUE TITLE
UploadImage

### ISSUE THREAD

**Issue by AlexMelw** [AlexMelw/ImageHost#1]

**Comment by AndreyWD** [comment]
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
- [ ] \(Optional) Open a followup issue

**Comment by AndreyWD** [comment]
@github/support sfsdfsd

**Comment by AndreyWD** [comment]
@AndreyWD lkmflskflksdflksdf

**Comment by AndreyWD** [comment]
@octocat :+1: This PR looks great - it's ready to merge! :shipit:

**Comment by AndreyWD** [comment]
@octocat :+1: 👍 This PR looks great - it's ready to merge! :shipit:

**Comment by AndreyWD** [comment]
First Header  | Second Header 
 ------------- | ------------- 
 Content Cell  | Content Cell  
 Content Cell  | Content Cell

**Comment by AndreyWD** [comment]
First Header  | Second Header 
 --- | ---
 Content Cell  | Content Cell  
 Content Cell  | Content Cell

**Comment by AndreyWD** [comment]
| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |

**Comment by AndreyWD** [comment]
![image](https://user-images.githubusercontent.com/15247302/60601614-13508500-9dbb-11e9-8d6e-c4da219dbae7.png | width=100)

**Comment by AndreyWD** [comment]
<img src="https://user-images.githubusercontent.com/15247302/60601614-13508500-9dbb-11e9-8d6e-c4da219dbae7.png" alt="" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />

**Comment by AndreyWD** [comment]
![image](https://user-images.githubusercontent.com/15247302/60603297-2e70c400-9dbe-11e9-9f86-e12d20d15a13.png)

**Comment by AndreyWD** [comment]
| Rejection Reason | Score | Status | Mouse Over Text |
| NULL | Greater or Equal than 80 | Checked - Passed | N/A |
| NULL | Less than 80 | Checked - Failed | No given reason |
| NOT NULL | N/A | Checked - Failed | <"Rejection Reason"> |

**Comment by AlexMelw** [comment]
![image](https://user-images.githubusercontent.com/15247302/80309103-64fb4d80-87db-11ea-856b-da1aeb5f0d28.png)

**Comment by AlexMelw** [comment]
Pattern to await a background worker or a thread from an asynchronous context
